- hosts: os
  vars_files:
          - "{{ansible_facts['distribution']}}-{{ansible_facts['distribution_major_version']}}.yml"
  tasks:
  - package:
      name: "{{ package }}"
      state: present
  - service:
      name: "{{ package }}"
      state: started

